### ISSUE TITLE
libprocps not available

### ISSUE THREAD

**Issue by mvenkita** [scipr-lab/libfqfft#2]
I am trying to install libfqfft on a unix distribution that is not ubuntu. I am not able to compile anything without libprocps which is available only for ubuntu. 
-- Checking for module 'libprocps'
--   No package 'libprocps' found
CMake Error at /gpfs/fs1/sfw/cmake/3.7.1/b1/share/cmake-3.7/Modules/FindPkgConfig.cmake:415 (message):
  A required package was not found
Call Stack (most recent call first):
  /gpfs/fs1/sfw/cmake/3.7.1/b1/share/cmake-3.7/Modules/FindPkgConfig.cmake:588 (_pkg_check_modules_internal)
  CMakeLists.txt:63 (pkg_check_modules)

-- Configuring incomplete, errors occurred!
See also "/home/mvenkita/sources/libfqfft/CMakeFiles/CMakeOutput.log".

**Comment by howardwu** [comment]
Thanks for bringing this to my attention. Which unix distro are you using?

If you don't need procps, I have flag guarded the procps requirement in both libff and libfqfft. Just use:
```
cmake .. -DWITH_PROCPS=OFF
```

If you need procps, this will likely be architecture specific. On Debian, there is procps-ng-devel. If you are able to resolve the dependency on your architecture, feel free to contribute by updating the README and sending a PR my way.

**Comment by mvenkita** [comment]
Hi Howard,

I get the following error when I try to compile libff (the dependency). I have installed boost.

CMake Warning at /gpfs/fs1/sfw/cmake/3.7.1/b1/share/cmake-3.7/Modules/FindBoost.cmake:744 (message):
  Imported targets not available for Boost version 106300
Call Stack (most recent call first):
  /gpfs/fs1/sfw/cmake/3.7.1/b1/share/cmake-3.7/Modules/FindBoost.cmake:848 (_Boost_COMPONENT_DEPENDENCIES)
  /gpfs/fs1/sfw/cmake/3.7.1/b1/share/cmake-3.7/Modules/FindBoost.cmake:1435 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:135 (FIND_PACKAGE)


-- Boost version: 1.63.0
-- Found the following Boost libraries:
--   program_options
CMake Error at third_party/CMakeLists.txt:1 (add_subdirectory):
  The source directory

    /home/mvenkita/sources/libff/third_party/gtest

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!

**Comment by howardwu** [comment]
It appears your gtest library was not installed fully. Can you try making the CMakeLists.txt and linking it as a shared library?
```
cd ${GTEST_DIR}
sudo cmake CMakeLists.txt
sudo make
sudo cp *.a /usr/lib # Copy/Symlink 'libgtest.a' and 'libgtest_main.a' into '/usr/lib'
```

There is also more documentation on gtest with cmake on their repo:
https://github.com/google/googletest/tree/aa148eb2b7f70ede0eb10de34b6254826bfb34f4/googletest

**Comment by mvenkita** [comment]
that worked. but when I make libff, i get the following error

[ 11%] Building CXX object src/CMakeFiles/ff.dir/algebra/curves/alt_bn128/alt_bn128_g1.cpp.o
In file included from /home/mvenkita/sources/libff/src/./algebra/curves/alt_bn128/alt_bn128_init.hpp:10,
                 from /home/mvenkita/sources/libff/src/./algebra/curves/alt_bn128/alt_bn128_g1.hpp:11,
                 from /home/mvenkita/sources/libff/src/algebra/curves/alt_bn128/alt_bn128_g1.cpp:8:
/home/mvenkita/sources/libff/src/./algebra/curves/public_params.hpp:72: error: expected unqualified-id before ‘using’
compilation terminated due to -Wfatal-errors.
make[2]: *** [src/CMakeFiles/ff.dir/algebra/curves/alt_bn128/alt_bn128_g1.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/ff.dir/all] Error 2

**Comment by howardwu** [comment]
Can you verify which compiler and version you're using?

This error seems to be related to the typename specifier and its instantiation. Are you use a c++11 compiler? Additionally can you verify your compiler version supports the described syntax? For example, if you're using gcc, check that it's >= 4.7.

On c++11, the below code **will not** work. But if you're using a different compiler and/or version, you can try replacing that code section with non-standard convention:
```cpp
template<typename EC_ppT>
using Fr = EC_ppT::Fp_type;
template<typename EC_ppT>
using G1 = EC_ppT::G1_type;
template<typename EC_ppT>
using G2 = EC_ppT::G2_type;
template<typename EC_ppT>
using G1_precomp = EC_ppT::G1_precomp_type;
template<typename EC_ppT>
using G2_precomp = EC_ppT::G2_precomp_type;
template<typename EC_ppT>
using affine_ate_G1_precomp = EC_ppT::affine_ate_G1_precomp_type;
template<typename EC_ppT>
using affine_ate_G2_precomp = EC_ppT::affine_ate_G2_precomp_type;
template<typename EC_ppT>
using Fq = EC_ppT::Fq_type;
template<typename EC_ppT>
using Fqe = EC_ppT::Fqe_type;
template<typename EC_ppT>
using Fqk = EC_ppT::Fqk_type;
template<typename EC_ppT>
using GT = EC_ppT::GT_type;
```

**Comment by mvenkita** [comment]
i use g++ 5.4.0
i had to manually change -std=c++11 to -std=c++0x
because i got the error

cc1plus: error: unrecognized command line option "-std=c++11”

so i changed it to std=c++0x and ran again when i got the error that I emailed you previously. here is my output for g++ version

[mvenkita@bluehive build]$ g++ --version
g++ (GCC) 5.4.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by howardwu** [comment]
That's perplexing. Just to check, when you cleanly run `cmake .. -DWITH_PROCPS=OFF`, does "The CXX compiler identification" also say 5.4.0?

Ex. on my machine:
```
$ cmake .. -DWITH_PROCPS=OFF
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
...
```

**Comment by mvenkita** [comment]
Hi Howard (cc:Scott)

My student Scott managed to install it. But he has the following issue. Thanks for your assistance.
_______

In our application we want to do FFT operations over a finite field of characteristic 2 that has a primitive 2^20th root of unity. The following is my first attempt at setting this up.

typedef libff::Double field_t;
shared_ptr<evaluation_domain<field_t>> domain = get_evaluation_domain<field_t>(size_t(1)<<20);

This code throws libfqfft::DomainSizeException. Do we need to specialize the evaluation_domain template (or possibly basic_radix2_domain) for the field that we want to use? Is there a better way?

_______


Muthu


-------- Original message --------

**Comment by howardwu** [comment]
I'm glad to hear you got that working!

There are two cases where DomainSizeException is thrown:
1) The domain size is legitimately a mismatch, which it shouldn't be in this case as we are considering 2^20.
2) The vector that you perform the FFT operation on is not of the same domain size. If you wanted a vector that is smaller, you'd want to zero-pad the vector up to domain size.

I presume your issue lies in case 2. Here is an example program for 2^20 running on my machine:
```cpp
#include <stdio.h>
#include <vector>

#include "common/double.hpp"

#include "../src/evaluation_domain/evaluation_domain.hpp"

using namespace libfqfft;

/* Fast, unsecure pseudorandom generator */
static unsigned int seed = 5149;
inline int fastrand()
{
  seed = (214013 * seed + 2531011);
  return (seed >> 16) & 0x7FFF;
}

/* Polynomial Evaluation */
template <typename FieldT>
void polynomial_evaluation_example ()
{
  /* Domain size */
  size_t m = size_t(1) << 20;

  /* Evaluation vector */
  std::vector<FieldT> f(m);
  for (size_t i = 0; i < m; i++)
  {
    f[i] = FieldT(fastrand());
  }

  /* Get evaluation domain */
  std::shared_ptr<evaluation_domain<FieldT> > domain = get_evaluation_domain<FieldT>(m);

  /* FFT */
  try
  {
    domain->FFT(f);
  }
  catch (DomainSizeException e) {
    printf("%s\n", e.what());
  }
  

  for (size_t i = 0; i < f.size(); i++)
  {
    printf("%ld: %ld\n", i, f[i].as_ulong());
  }
}

int main()
{
  polynomial_evaluation_example<libff::Double> ();
}
```

**Comment by mvenkita** [comment]
Hey Howard,

Thanks for the code. We would like to do FFT in the finite field GF(2^n). For example n=40 and we want to do a FFT over vector of length 2^10.
Could you tell how to use your implementation (I am assuming we want to use the geometric sequence domain but I am not sure how to use it).

We are trying to compare the running times with NTL’s implementation of FFT.

Thanks
-Muthu

**Comment by howardwu** [comment]
If you plan to run FFT on a vector of size 2^10, you'll need to pad it to the domain size. 

To bypass the automated selection of the evaluation domain, you can invoke your choice of domain directly, without using a shared pointer. Just instantiate the domain and pass the domain size as a parameter to the constructor, then run `domain.FFT(f)` for the vector f.

As a side technical point, performing FFT on a domain size of 2^40 is nontrivial, and you'll likely hit memory thresholds of your machine around domain size 2^24. In this case, you may be better off using a distributed implementation of FFT in finite fields on a compute cluster instead.

**Comment by howardwu** [comment]
Marking resolved.

**Comment by mvenkita** [comment]
Thanks.

-Muthu
